// <auto-generated />
namespace WebAPP_LIULI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init22));
        
        string IMigrationMetadata.Id
        {
            get { return "202003120300109_init22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
